- name: "HIGH | PGS9-00-000300 | Security-relevant software updates to PostgreSQL must be installed within the time period directed by an authoritative source (e.g., IAVM, CTOs, DTMs, and STIGs)."
  block:
      - name: "HIGH | PGS9-00-000300 | AUDIT | Security-relevant software updates to PostgreSQL must be installed within the time period directed by an authoritative source (e.g., IAVM, CTOs, DTMs, and STIGs)."
        command: "true"
        register: pgs9_00_000300_audit
        check_mode: no
        changed_when: no
        with_items:
            - not implemented
      - name: "HIGH | PGS9-00-000300 | PATCH | Security-relevant software updates to PostgreSQL must be installed within the time period directed by an authoritative source (e.g., IAVM, CTOs, DTMs, and STIGs)."
        command: "true"
        changed_when: no
        with_items:
            - not implemented
  when:
      - pgs9_00_000300
  tags:
      - PGS9-00-000300
      - notimplemented

- name: "HIGH | PGS9-00-008000 | PostgreSQL must implement NIST FIPS 140-2 validated cryptographic modules to generate and validate cryptographic hashes."
  block:
      - name: "HIGH | PGS9-00-008000 | AUDIT | PostgreSQL must implement NIST FIPS 140-2 validated cryptographic modules to generate and validate cryptographic hashes."
        command: "true"
        register: pgs9_00_008000_audit
        check_mode: no
        changed_when: no
        with_items:
            - not implemented
      - name: "HIGH | PGS9-00-008000 | PATCH | PostgreSQL must implement NIST FIPS 140-2 validated cryptographic modules to generate and validate cryptographic hashes."
        command: "true"
        changed_when: no
        with_items:
            - not implemented
  when:
      - pgs9_00_008000
  tags:
      - PGS9-00-008000
      - notimplemented

- name: "HIGH | PGS9-00-008200 | PostgreSQL must implement NIST FIPS 140-2 validated cryptographic modules to protect unclassified information requiring confidentiality and cryptographic protection, in accordance with the data owners requirements."
  block:
      - name: "HIGH | PGS9-00-008200 | AUDIT | PostgreSQL must implement NIST FIPS 140-2 validated cryptographic modules to protect unclassified information requiring confidentiality and cryptographic protection, in accordance with the data owners requirements."
        command: "true"
        register: pgs9_00_008200_audit
        check_mode: no
        changed_when: no
        with_items:
            - not implemented
      - name: "HIGH | PGS9-00-008200 | PATCH | PostgreSQL must implement NIST FIPS 140-2 validated cryptographic modules to protect unclassified information requiring confidentiality and cryptographic protection, in accordance with the data owners requirements."
        command: "true"
        changed_when: no
        with_items:
            - not implemented
  when:
      - pgs9_00_008200
  tags:
      - PGS9-00-008200
      - notimplemented

- name: "HIGH | PGS9-00-010200 | PostgreSQL must enforce authorized access to all PKI private keys stored/utilized by PostgreSQL."
  block:
      - name: "HIGH | PGS9-00-010200 | AUDIT | PostgreSQL must enforce authorized access to all PKI private keys stored/utilized by PostgreSQL."
        command: "true"
        register: pgs9_00_010200_audit
        check_mode: no
        changed_when: no
        with_items:
            - not implemented
      - name: "HIGH | PGS9-00-010200 | PATCH | PostgreSQL must enforce authorized access to all PKI private keys stored/utilized by PostgreSQL."
        command: "true"
        changed_when: no
        with_items:
            - not implemented
  when:
      - pgs9_00_010200
  tags:
      - PGS9-00-010200
      - notimplemented

- name: "HIGH | PGS9-00-011700 | PostgreSQL must prevent non-privileged users from executing privileged functions, to include disabling, circumventing, or altering implemented security safeguards/countermeasures."
  block:
      - name: "HIGH | PGS9-00-011700 | AUDIT | PostgreSQL must prevent non-privileged users from executing privileged functions, to include disabling, circumventing, or altering implemented security safeguards/countermeasures."
        command: "true"
        register: pgs9_00_011700_audit
        check_mode: no
        changed_when: no
        with_items:
            - not implemented
      - name: "HIGH | PGS9-00-011700 | PATCH | PostgreSQL must prevent non-privileged users from executing privileged functions, to include disabling, circumventing, or altering implemented security safeguards/countermeasures."
        command: "true"
        changed_when: no
        with_items:
            - not implemented
  when:
      - pgs9_00_011700
  tags:
      - PGS9-00-011700
      - notimplemented

- name: "HIGH | PGS9-00-012300 | PostgreSQL must use NIST FIPS 140-2 validated cryptographic modules for cryptographic operations."
  block:
      - name: "HIGH | PGS9-00-012300 | AUDIT | PostgreSQL must use NIST FIPS 140-2 validated cryptographic modules for cryptographic operations."
        command: "true"
        register: pgs9_00_012300_audit
        check_mode: no
        changed_when: no
        with_items:
            - not implemented
      - name: "HIGH | PGS9-00-012300 | PATCH | PostgreSQL must use NIST FIPS 140-2 validated cryptographic modules for cryptographic operations."
        command: "true"
        changed_when: no
        with_items:
            - not implemented
  when:
      - pgs9_00_012300
  tags:
      - PGS9-00-012300
      - notimplemented

- name: "HIGH | PGS9-00-012800 | The DBMS must be configured on a platform that has a NIST certified FIPS 140-2 installation of OpenSSL."
  block:
      - name: "HIGH | PGS9-00-012800 | AUDIT | The DBMS must be configured on a platform that has a NIST certified FIPS 140-2 installation of OpenSSL."
        command: "true"
        register: pgs9_00_012800_audit
        check_mode: no
        changed_when: no
        with_items:
            - not implemented
      - name: "HIGH | PGS9-00-012800 | PATCH | The DBMS must be configured on a platform that has a NIST certified FIPS 140-2 installation of OpenSSL."
        command: "true"
        changed_when: no
        with_items:
            - not implemented
  when:
      - pgs9_00_012800
  tags:
      - PGS9-00-012800
      - notimplemented

