---

- name: "PRELIM | Gather mount information"
  setup:
      gather_subset: hardware,!all,!min
      filter: ansible_mounts
  when:
      - ansible_mounts is not defined
      - pgs9_00_008000 or
        pgs9_00_008200
  tags:
      - cat1
      - high
      - PGS9-00-008000
      - PGS9-00-008200

- name: "PRELIM | PGS9-00-008000 | Check if /boot or /boot/efi reside on separate partitions"
  shell: df --output=target /boot | tail -n 1
  changed_when: no
  check_mode: no
  register: pgs9_00_boot_part
  when:
      - pgs9_00_008000 or
        pgs9_00_008200
  tags:
      - cat1
      - high
      - PGS9-00-008000
      - PGS9-00-008200

- name: "PRELIM | Appendix F: Finding the PostgreSQL Configured Data Directory (PGDATA)"
  block:
      - name: "PRELIM | Ensure postgres is started"
        service:
            name: "{{ pgs9stig_postgres_service }}"
            state: started

      - name: "PRELIM | Appendix F: Finding the PostgreSQL Configured Data Directory (PGDATA)"
        shell: psql -c 'show data_directory' | tail -n+3 | head -n 1 | cut -c2-
        check_mode: no
        changed_when: no
        register: pgs9stig_pgdata_cmd
        become: yes
        become_user: postgres

      - name: "PRELIM | make pgdata available as variable"
        set_fact:
            pgs9stig_pgdata: "{{ pgs9stig_pgdata_cmd.stdout }}"
  when: pgs9stig_pgdata is not defined
  tags:
      - always

- name: "PRELIM | Appendix C: Logging"
  block:
      - name: "PRELIM | Appendix C: Logging | stderr"
        lineinfile:
            path: "{{ pgs9stig_pgdata }}/postgresql.conf"
        module_defaults: "{{ pgs9stig_lineinfile }}"
        notify: reload postgres
        with_dict:
            log_destination: "'stderr'"
            logging_collector: "on"
            log_directory: "'pg_log'"
            log_filename: "'postgresql-%a.log'"
            log_file_mode: "0600"
            log_truncate_on_rotation: "on"
            log_rotation_age: "1d"
            log_rotation_size: 0
        when: pgs9stig_log_destination == 'stderr'

      - name: "PRELIM | Appendix C: Logging | syslog"
        lineinfile:
            path: "{{ pgs9stig_pgdata }}/postgresql.conf"
        module_defaults: "{{ pgs9stig_lineinfile }}"
        notify: reload postgres
        with_dict:
            log_destination: "'syslog'"
            syslog_facility: "'LOCAL0'"
            syslog_ident: "'postgres'"
        when: pgs9stig_log_destination == 'syslog'

      - name: "PRELIM | Appendix C: Logging | rsyslog"
        block:
            - name: "PRELIM | Appendix C: Logging | install rsyslog"
              yum:
                  name: rsyslog

            - name: "PRELIM | Appendix C: Logging | configure rsyslog"
              blockinfile:
                  path: "{{ pgs9stig_rsyslog_conf }}"
                  create: yes
                  mode: 0644
                  block: |
                      # Log postgres items to file
                      local0.*                                                {{ pgs9stig_rsyslog_log_path }}
              notify: restart rsyslog

            - name: "PRELIM | Appendix C: Logging | start rsyslog"
              service:
                  name: rsyslog
                  state: started

            - name: "PRELIM | Appendix C: Logging | configure logrotate"
              lineinfile:
                  path: /etc/logrotate.d/syslog
                  insertbefore: ^{$
                  line: "{{ pgs9stig_rsyslog_log_path }}"
        when: pgs9stig_with_rsyslog
  when:
      - pgs9_00_000400 or
        pgs9_00_003700 or
        pgs9_00_004200 or
        pgs9_00_004500 or
        pgs9_00_004600 or
        pgs9_00_004700 or
        pgs9_00_004800 or
        pgs9_00_005100 or
        pgs9_00_005300 or
        pgs9_00_005400 or
        pgs9_00_005700 or
        pgs9_00_006200 or
        pgs9_00_006500 or
        pgs9_00_010400 or
        pgs9_00_011300 or
        false
  tags:
      - PGS9-00-000400
      - PGS9-00-003700
      - PGS9-00-004200
      - PGS9-00-004500
      - PGS9-00-004600
      - PGS9-00-004700
      - PGS9-00-004800
      - PGS9-00-005100
      - PGS9-00-005300
      - PGS9-00-005400
      - PGS9-00-005700
      - PGS9-00-006200
      - PGS9-00-006500
      - PGS9-00-010400
      - PGS9-00-011300
