---

- name: "PRELIM | Gather mount information"
  setup:
      gather_subset: hardware,!all,!min
      filter: ansible_mounts
  when:
      - ansible_mounts is not defined
  tags:
      - always

- name: "PRELIM | PGS9-00-008000 | Check if /boot or /boot/efi reside on separate partitions"
  shell: df --output=target /boot | tail -n 1
  changed_when: no
  check_mode: no
  register: pgs9_00_boot_part
  when:
      - pgs9_00_008000
  tags:
      - cat1
      - high
      - PGS9-00-008000

- name: "PRELIM | Appendix F: Finding the PostgreSQL Configured Data Directory (PGDATA)"
  block:
      - name: "PRELIM | Ensure postgres is started"
        service:
            name: "{{ pgs9stig_postgres_service }}"
            state: started

      - name: "PRELIM | Appendix F: Finding the PostgreSQL Configured Data Directory (PGDATA)"
        shell: psql -c 'show data_directory' | tail -n+3 | head -n 1 | cut -c2-
        check_mode: no
        changed_when: no
        register: pgs9stig_pgdata_cmd
        become: yes
        become_user: postgres

      - name: "PRELIM | make pgdata available as variable"
        set_fact:
            pgs9stig_pgdata: "{{ pgs9stig_pgdata_cmd.stdout }}"
  when: pgs9stig_pgdata is not defined
  tags:
      - always
