---
- name: restart postgres
  service:
      name: "{{ pgs9stig_postgres_service }}"
      state: restarted

- name: reload postgres
  service:
      name: "{{ pgs9stig_postgres_service }}"
      state: reloaded
